<?php

use Illuminate\Database\Seeder;
use papusclub\Models\Provincia;

class ProvinciaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Provincia::create(['id'=>'1', 'nombre'=>'CHACHAPOYAS ', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'2', 'nombre'=>'BAGUA', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'3', 'nombre'=>'BONGARA', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'4', 'nombre'=>'CONDORCANQUI', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'5', 'nombre'=>'LUYA', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'6', 'nombre'=>'RODRIGUEZ DE MENDOZA', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'7', 'nombre'=>'UTCUBAMBA', 'departamento_id'=>'1']);
		Provincia::create(['id'=>'8', 'nombre'=>'HUARAZ', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'9', 'nombre'=>'AIJA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'10', 'nombre'=>'ANTONIO RAYMONDI', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'11', 'nombre'=>'ASUNCION', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'12', 'nombre'=>'BOLOGNESI', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'13', 'nombre'=>'CARHUAZ', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'14', 'nombre'=>'CARLOS FERMIN FITZCARRALD', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'15', 'nombre'=>'CASMA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'16', 'nombre'=>'CORONGO', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'17', 'nombre'=>'HUARI', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'18', 'nombre'=>'HUARMEY', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'19', 'nombre'=>'HUAYLAS', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'20', 'nombre'=>'MARISCAL LUZURIAGA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'21', 'nombre'=>'OCROS', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'22', 'nombre'=>'PALLASCA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'23', 'nombre'=>'POMABAMBA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'24', 'nombre'=>'RECUAY', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'25', 'nombre'=>'SANTA', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'26', 'nombre'=>'SIHUAS', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'27', 'nombre'=>'YUNGAY', 'departamento_id'=>'2']);
		Provincia::create(['id'=>'28', 'nombre'=>'ABANCAY', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'29', 'nombre'=>'ANDAHUAYLAS', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'30', 'nombre'=>'ANTABAMBA', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'31', 'nombre'=>'AYMARAES', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'32', 'nombre'=>'COTABAMBAS', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'33', 'nombre'=>'CHINCHEROS', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'34', 'nombre'=>'GRAU', 'departamento_id'=>'3']);
		Provincia::create(['id'=>'35', 'nombre'=>'AREQUIPA', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'36', 'nombre'=>'CAMANA', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'37', 'nombre'=>'CARAVELI', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'38', 'nombre'=>'CASTILLA', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'39', 'nombre'=>'CAYLLOMA', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'40', 'nombre'=>'CONDESUYOS', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'41', 'nombre'=>'ISLAY', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'42', 'nombre'=>'LA UNION', 'departamento_id'=>'4']);
		Provincia::create(['id'=>'43', 'nombre'=>'HUAMANGA', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'44', 'nombre'=>'CANGALLO', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'45', 'nombre'=>'HUANCA SANCOS', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'46', 'nombre'=>'HUANTA', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'47', 'nombre'=>'LA MAR', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'48', 'nombre'=>'LUCANAS', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'49', 'nombre'=>'PARINACOCHAS', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'50', 'nombre'=>'PAUCAR DEL SARA SARA', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'51', 'nombre'=>'SUCRE', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'52', 'nombre'=>'VICTOR FAJARDO', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'53', 'nombre'=>'VILCAS HUAMAN', 'departamento_id'=>'5']);
		Provincia::create(['id'=>'54', 'nombre'=>'CAJAMARCA', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'55', 'nombre'=>'CAJABAMBA', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'56', 'nombre'=>'CELENDIN', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'57', 'nombre'=>'CHOTA ', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'58', 'nombre'=>'CONTUMAZA', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'59', 'nombre'=>'CUTERVO', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'60', 'nombre'=>'HUALGAYOC', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'61', 'nombre'=>'JAEN', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'62', 'nombre'=>'SAN IGNACIO', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'63', 'nombre'=>'SAN MARCOS', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'64', 'nombre'=>'SAN MIGUEL', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'65', 'nombre'=>'SAN PABLO', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'66', 'nombre'=>'SANTA CRUZ', 'departamento_id'=>'6']);
		Provincia::create(['id'=>'67', 'nombre'=>'CALLAO', 'departamento_id'=>'7']);
		Provincia::create(['id'=>'68', 'nombre'=>'CUSCO', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'69', 'nombre'=>'ACOMAYO', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'70', 'nombre'=>'ANTA', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'71', 'nombre'=>'CALCA', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'72', 'nombre'=>'CANAS', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'73', 'nombre'=>'CANCHIS', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'74', 'nombre'=>'CHUMBIVILCAS', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'75', 'nombre'=>'ESPINAR', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'76', 'nombre'=>'LA CONVENCION', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'77', 'nombre'=>'PARURO', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'78', 'nombre'=>'PAUCARTAMBO', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'79', 'nombre'=>'QUISPICANCHI', 'departamento_id'=>'8']);
		//Provincia::create(['id'=>'80', 'nombre'=>'URUBAMBA', 'departamento_id'=>'8']);
		Provincia::create(['id'=>'80', 'nombre'=>'HUANCAVELICA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'81', 'nombre'=>'ACOBAMBA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'82', 'nombre'=>'ANGARAES', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'83', 'nombre'=>'CASTROVIRREYNA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'84', 'nombre'=>'CHURCAMPA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'85', 'nombre'=>'HUAYTARA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'86', 'nombre'=>'TAYACAJA', 'departamento_id'=>'9']);
		Provincia::create(['id'=>'87', 'nombre'=>'HUANUCO', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'88', 'nombre'=>'AMBO', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'89', 'nombre'=>'DOS DE MAYO', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'90', 'nombre'=>'HUACAYBAMBA', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'91', 'nombre'=>'HUAMALIES', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'92', 'nombre'=>'LEONCIO PRADO', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'93', 'nombre'=>'MARA&Ntilde;ON', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'94', 'nombre'=>'PACHITEA', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'95', 'nombre'=>'PUERTO INCA', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'96', 'nombre'=>'LAURICOCHA', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'97', 'nombre'=>'YAROWILCA', 'departamento_id'=>'10']);
		Provincia::create(['id'=>'98', 'nombre'=>'ICA', 'departamento_id'=>'11']);
		Provincia::create(['id'=>'99', 'nombre'=>'CHINCHA', 'departamento_id'=>'11']);
		Provincia::create(['id'=>'100', 'nombre'=>'NAZCA', 'departamento_id'=>'11']);
		Provincia::create(['id'=>'101', 'nombre'=>'PALPA', 'departamento_id'=>'11']);
		Provincia::create(['id'=>'102', 'nombre'=>'PISCO', 'departamento_id'=>'11']);
		Provincia::create(['id'=>'103', 'nombre'=>'HUANCAYO', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'104', 'nombre'=>'CONCEPCION', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'105', 'nombre'=>'CHANCHAMAYO', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'106', 'nombre'=>'JAUJA', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'107', 'nombre'=>'JUNIN', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'108', 'nombre'=>'SATIPO', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'109', 'nombre'=>'TARMA', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'110', 'nombre'=>'YAULI', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'111', 'nombre'=>'CHUPACA', 'departamento_id'=>'12']);
		Provincia::create(['id'=>'112', 'nombre'=>'TRUJILLO', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'113', 'nombre'=>'ASCOPE', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'114', 'nombre'=>'BOLIVAR', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'115', 'nombre'=>'CHEPEN', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'116', 'nombre'=>'JULCAN', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'117', 'nombre'=>'OTUZCO', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'118', 'nombre'=>'PACASMAYO', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'119', 'nombre'=>'PATAZ', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'120', 'nombre'=>'SANCHEZ CARRION', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'121', 'nombre'=>'SANTIAGO DE CHUCO', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'122', 'nombre'=>'GRAN CHIMU', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'123', 'nombre'=>'VIRU', 'departamento_id'=>'13']);
		Provincia::create(['id'=>'124', 'nombre'=>'CHICLAYO', 'departamento_id'=>'14']);
		Provincia::create(['id'=>'125', 'nombre'=>'FERRE&Ntilde;AFE', 'departamento_id'=>'14']);
		Provincia::create(['id'=>'126', 'nombre'=>'LAMBAYEQUE', 'departamento_id'=>'14']);
		Provincia::create(['id'=>'127', 'nombre'=>'LIMA', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'128', 'nombre'=>'BARRANCA', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'129', 'nombre'=>'CAJATAMBO', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'130', 'nombre'=>'CANTA', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'131', 'nombre'=>'CA&Ntilde;ETE', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'132', 'nombre'=>'HUARAL', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'133', 'nombre'=>'HUAROCHIRI', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'134', 'nombre'=>'HUAURA', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'135', 'nombre'=>'OYON', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'136', 'nombre'=>'YAUYOS', 'departamento_id'=>'15']);
		Provincia::create(['id'=>'137', 'nombre'=>'MAYNAS', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'138', 'nombre'=>'ALTO AMAZONAS', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'139', 'nombre'=>'LORETO', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'140', 'nombre'=>'MARISCAL RAMON CASTILLA', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'141', 'nombre'=>'REQUENA', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'142', 'nombre'=>'UCAYALI', 'departamento_id'=>'16']);
		Provincia::create(['id'=>'143', 'nombre'=>'TAMBOPATA', 'departamento_id'=>'17']);
		Provincia::create(['id'=>'144', 'nombre'=>'MANU', 'departamento_id'=>'17']);
		Provincia::create(['id'=>'145', 'nombre'=>'TAHUAMANU', 'departamento_id'=>'17']);
		Provincia::create(['id'=>'146', 'nombre'=>'MARISCAL NIETO', 'departamento_id'=>'18']);
		Provincia::create(['id'=>'147', 'nombre'=>'GENERAL SANCHEZ CERRO', 'departamento_id'=>'18']);
		Provincia::create(['id'=>'148', 'nombre'=>'ILO', 'departamento_id'=>'18']);
		Provincia::create(['id'=>'149', 'nombre'=>'PASCO', 'departamento_id'=>'19']);
		Provincia::create(['id'=>'150', 'nombre'=>'DANIEL ALCIDES CARRION', 'departamento_id'=>'19']);
		Provincia::create(['id'=>'151', 'nombre'=>'OXAPAMPA', 'departamento_id'=>'19']);
		Provincia::create(['id'=>'152', 'nombre'=>'PIURA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'153', 'nombre'=>'AYABACA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'154', 'nombre'=>'HUANCABAMBA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'155', 'nombre'=>'MORROPON', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'156', 'nombre'=>'PAITA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'157', 'nombre'=>'SULLANA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'158', 'nombre'=>'TALARA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'159', 'nombre'=>'SECHURA', 'departamento_id'=>'20']);
		Provincia::create(['id'=>'160', 'nombre'=>'PUNO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'161', 'nombre'=>'AZANGARO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'162', 'nombre'=>'CARABAYA', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'163', 'nombre'=>'CHUCUITO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'164', 'nombre'=>'EL COLLAO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'165', 'nombre'=>'HUANCANE', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'166', 'nombre'=>'LAMPA', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'167', 'nombre'=>'MELGAR', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'168', 'nombre'=>'MOHO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'169', 'nombre'=>'SAN ANTONIO DE PUTINA', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'170', 'nombre'=>'SAN ROMAN', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'171', 'nombre'=>'SANDIA', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'172', 'nombre'=>'YUNGUYO', 'departamento_id'=>'21']);
		Provincia::create(['id'=>'173', 'nombre'=>'MOYOBAMBA', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'174', 'nombre'=>'BELLAVISTA', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'175', 'nombre'=>'EL DORADO', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'176', 'nombre'=>'HUALLAGA', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'177', 'nombre'=>'LAMAS', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'178', 'nombre'=>'MARISCAL CACERES', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'179', 'nombre'=>'PICOTA', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'180', 'nombre'=>'RIOJA', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'181', 'nombre'=>'SAN MARTIN', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'182', 'nombre'=>'TOCACHE', 'departamento_id'=>'22']);
		Provincia::create(['id'=>'183', 'nombre'=>'TACNA', 'departamento_id'=>'23']);
		Provincia::create(['id'=>'184', 'nombre'=>'CANDARAVE', 'departamento_id'=>'23']);
		Provincia::create(['id'=>'185', 'nombre'=>'JORGE BASADRE', 'departamento_id'=>'23']);
		Provincia::create(['id'=>'186', 'nombre'=>'TARATA', 'departamento_id'=>'23']);
		Provincia::create(['id'=>'187', 'nombre'=>'TUMBES', 'departamento_id'=>'24']);
		Provincia::create(['id'=>'188', 'nombre'=>'CONTRALMIRANTE VILLAR', 'departamento_id'=>'24']);
		Provincia::create(['id'=>'189', 'nombre'=>'ZARUMILLA', 'departamento_id'=>'24']);
		Provincia::create(['id'=>'190', 'nombre'=>'CORONEL PORTILLO', 'departamento_id'=>'25']);
		Provincia::create(['id'=>'191', 'nombre'=>'ATALAYA', 'departamento_id'=>'25']);
		Provincia::create(['id'=>'192', 'nombre'=>'PADRE ABAD', 'departamento_id'=>'25']);
		Provincia::create(['id'=>'193', 'nombre'=>'PURUS', 'departamento_id'=>'25']);
    }
}
